### ISSUE TITLE
Videoes stream error

### ISSUE THREAD

**Issue by lucaskyle** [swook/GazeML#28]
i have tried so many videos i got.
it shows so many different error...

one is like:

threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "elg_demo.py", line 224, in _visualize_output
    bgr[v1:v2, u0:u1] = eye_image_annotated
ValueError: could not broadcast input array from shape (216,360,3) into shape (72,360,3)

second is like:

Video "xxxxxxxxxxxxxxxxx.mp4" closed.

**Comment by lucaskyle** [comment]
i wonder if the video should be one person with a pair of eyes?

**Comment by lucaskyle** [comment]
atctually，after I install the latest Version of tensorflow,   and  reinstall opencv-python , i fixed the problem.
im so sorry

**Comment by keishatsai** [comment]
Hi @lucaskyle 

I quite got the same problem with you. I only got "Video "xxxxxxxxxxxxxxxxx.mp4" closed." when I tried to run elg_demo.py. Have you also encountered this situation? 

Thank you.

**Comment by keishatsai** [comment]
@lucaskyle 
Could you tell me which version of tensorflow and opencv are you using for this case?
Thanks.

**Comment by lucaskyle** [comment]
@keishatsai 
tensorflow-gpu            1.9.0  
opencv                    3.4.3 

sorry, I'm so late answering u

**Comment by keishatsai** [comment]
@lucaskyle Thank you. 
Did you install the latest version? Do you mean tensorflow-gpu1.9.0 is the latest one to solve your problem?
Mine is tensorflow-gpu 1.14.0 and the issue is still not solved.
Could you share your command also? Just want to make sure that I am on the right track.
